### ISSUE TITLE
 pDefaultAppDomain->Load_3(...) failed

### ISSUE THREAD

**Issue by EgeBalci** [etormadiv/HostingCLR#1]
It is not loading the assembly what do you think could be the reason of this ?
I didn't change any of the code, i am using windows 7 and .NET 4.5/4.6. 

![image](https://user-images.githubusercontent.com/17179401/30203691-8b6fa31c-948b-11e7-81e8-3075ff6ba1e5.png)
I used a simple hello world C# binary.
![image](https://user-images.githubusercontent.com/17179401/30203747-cb5e2354-948b-11e7-84d2-4261ead89655.png)
appreciate your help.

**Comment by etormadiv** [comment]
Make sure you initialized the rawData array with your .net assembly as bytes.

```
unsigned char rawData[8192] = { //Copy your assembly length
	//...
};
```

Also make sure to change the value of `RAW_ASSEMBLY_LENGTH ` accordingly to the rawData length.

`#define RAW_ASSEMBLY_LENGTH 8192 //Change the value to your assembly length
`

**Comment by EgeBalci** [comment]
I have done that with a new header file, initiated the array just like you sad but still the same error :(

![image](https://user-images.githubusercontent.com/17179401/30227902-2251d25c-94e4-11e7-8e10-9bead7a3fdd7.png)

Do you know a way to debug this Load_3 function like getting the error code or something ?

**Comment by etormadiv** [comment]
Well, you probably didn't changed the `cElements` argument, from your hello world source I can see that Main method has the args (Main has one argument), so you must change `cElements` to `1` in this line https://github.com/etormadiv/HostingCLR/blob/master/HostingCLR/HostingCLR.cpp#L219

But, in the case of a Windows Forms Application, the Main has zero arguments by default, and you will want to change `cElements` to `0` then.

`cElements ` is the third argument of the [`SafeArrayCreateVector`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms221558(v=vs.85).aspx) function.

**Comment by EgeBalci** [comment]
Unfortunately this did not work either :/

![image](https://user-images.githubusercontent.com/17179401/30229225-b79a5e6a-94e9-11e7-8721-32cc7a834831.png)

Maybe this is about VisualStudio version related.

**Comment by etormadiv** [comment]
I see that Visual studio is underlining some parts of the code, are you sure you are running the full solution or it is just copy past of one file ? maybe you need to change your stdafx.h according to this one: https://github.com/etormadiv/HostingCLR/blob/master/HostingCLR/stdafx.h

**Comment by EgeBalci** [comment]
I am using exactly the same code inside the git repo, at first  i also noticed there are several syntax error highlighting on visual studio but when it compiled successfully i tout it is irrelevant, it seems the reason for syntax errors are visual studio is unable to open the `mscorlib.tlb` file

![image](https://user-images.githubusercontent.com/17179401/30230543-6f23b1e4-94ef-11e7-81fc-3e6336c372fb.png)

But i do have the file inside the specified directory :S 

![image](https://user-images.githubusercontent.com/17179401/30230646-d58b9af0-94ef-11e7-96f3-b552da708be1.png)

This must be about the version of the visual studio, do you remember the version you build this ?

**Comment by etormadiv** [comment]
Just [**download the whole repository**](https://github.com/etormadiv/HostingCLR/archive/master.zip), the solution is built using VS2010, but I tested it under VS2015 and it worked, VS2015 or any later version will do the upgrade for you so you should not worry about the version.

Update: Also make sure that the target version of .net assembly is v2.0, since the code is hosting the .net runtime v2.0.50727.
