### ISSUE TITLE
pMethodInfo->Invoke_3(...) failed, hr = 80131604

### ISSUE THREAD

**Issue by mekkolodziejski** [etormadiv/HostingCLR#3]
Hello i have error

**Comment by Sonic-The-Hedgehog-LNK1123** [comment]
For other people having this problem, it's probably because you tried to load a .NET 4.0+ assembly in the 2.0 runtime, at least that was the problem I had.

To fix it, change this line in `HostingCLR.cpp`:
```C++
hr = pMetaHost->GetRuntime(L"v2.0.50727", IID_ICLRRuntimeInfo, (VOID**)&pRuntimeInfo);
```
to:
```C++
hr = pMetaHost->GetRuntime(L"v4.0.30319", IID_ICLRRuntimeInfo, (VOID**)&pRuntimeInfo);
```
